<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Strict by default. -->
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-recommended</AnalysisLevel>

    <!-- XML-doc is mandatory on public API. CS1591 = missing XML comment. -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <!-- Deterministic, source-link friendly. -->
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>

    <RootNamespace>$(MSBuildProjectName)</RootNamespace>
  </PropertyGroup>

  <!-- Package metadata (applies to packable projects only). -->
  <PropertyGroup>
	<Version>1.0.0</Version>
    <Authors>VinDust</Authors>
    <Company>VinDust</Company>
    <Product>SharpVfs</Product>
	<PackageOutputPath>$(MSBuildThisFileDirectory)local-packages</PackageOutputPath>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/VinDustVSD/SharpVfs</PackageProjectUrl>
    <RepositoryUrl>https://github.com/VinDustVSD/SharpVfs</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>vfs;virtual-file-system;filesystem;zip;union-mount</PackageTags>
  </PropertyGroup>

</Project>