<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>DeltaBuilder.Sample</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\VinDust.SharpVfs.Abstractions\VinDust.SharpVfs.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\VinDust.SharpVfs.Core\VinDust.SharpVfs.Core.csproj" />
    <ProjectReference Include="..\..\src\VinDust.SharpVfs.FileSystems.Physical\VinDust.SharpVfs.FileSystems.Physical.csproj" />
    <ProjectReference Include="..\..\src\VinDust.SharpVfs.FileSystems.Zip\VinDust.SharpVfs.FileSystems.Zip.csproj" />
  </ItemGroup>

</Project>